site:
  title: 在路上的官方网站
  description: 在路上的官方网站 (ontheway.com) 分享技术、生活和思考
  keywords: 在路上, ontheway, 技术, 生活, 思考, 博客, 写作
  theme: default
  language: zh-CN
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  root-path: /dailyshells.com
  # set cdn prefix: self hosted
  cdn-path: /dailyshells.com/static
  navigation:
    - title: 技术
      uri: /blogs/tech/index.html
    - title: 格局打开
      uri: /blogs/How2MakeMoney/index.html
    # - title: Java教程
    #   uri: /books/java/index.html
    # - title: Python教程
    #   uri: /books/python/index.html
    # - title: JavaScript教程
    #   uri: /books/javascript/index.html
    # - title: SQL教程
    #   uri: /books/sql/index.html
    # - title: 手写Spring
    #   uri: /books/summerframework/index.html
    # - title: 手写Tomcat
    #   uri: /books/jerrymouse/index.html
    # - title: 区块链教程
    #   uri: /books/blockchain/index.html
    # - title: Git教程
    #   uri: /books/git/index.html
    # - title: Makefile教程
    #   uri: /books/makefile/index.html
    # - title: 博客
    #   uri: /blogs/all/index.html
  git:
    base-url: https://github.com/OnTheWay0103/dailyshells.com/blob/main/source
  contact:
    name: 在路上
    github: https://github.com/OnTheWay0103/dailyshells.com.git
    twitter: https://twitter.com/ontheway
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: false
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: oauth
      url: https://api.ontheway.com
    analytics:
      provider: google
      id: "G-XXXXXXXXXX" # 这里需要替换为您的Google Analytics ID
  footer: |
    <div>
      &copy;<a href="/">ontheway.com</a> 
      - <a href="https://weibo.com/ontheway" target="_blank">微博</a>
      - <a href="https://github.com/OnTheWay0103/dailyshells.com.git" target="_blank">GitHub</a>
      - <a href="/pages/license/index.html" target="_blank">License</a>
    </div>

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt
# you can add any items:
