# Workflow for building and deploying a GitSite repo to GitHub Pages

name: Build liaoxuefeng.com

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    steps:
      - name: Setup Env
        run:
          echo "RELEASE_AT=`echo ${{ github.event.head_commit.timestamp }} | sed 's/[:+]/-/g'`" >> "$GITHUB_ENV"
          echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> "$GITHUB_ENV"
      - name: Print Env
        run:
          echo ${{ env.RELEASE_AT }}
          echo ${{ env.SHORT_SHA }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install GitSite
        run:
          npm install gitsite-cli -g
      - name: Build with GitSite
        run:
          # set output dir to '_site' for pages jobs:
          gitsite-cli build -o _site
      - name: Zip Generated Site
        run:
          cd _site && zip -r ../site-${{ env.SHORT_SHA }}.zip * && cd ..
      - name: Release Zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: site-${{ env.SHORT_SHA }}.zip
          tag: ${{ github.ref }}.${{ github.sha }}
          overwrite: true

  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
