# Sample workflow for building and deploying a GitSite repo to GitHub Pages
#
# To get started with GitSite see: https://gitsite.org

name: Build by GitSite

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Setup Env
        run:
          echo "RELEASE_AT=`echo ${{ github.event.repository.updated_at }} | sed 's/:/-/g'`" >> "$GITHUB_ENV"
          echo ${{ env.RELEASE_AT }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install GitSite
        run:
          npm install gitsite-cli -g
      - name: Build with GitSite
        run:
          # set output dir to '_site' for pages jobs:
          gitsite-cli build -o _site
      - name: Zip Generated Site
        run:
          tar zcvf site.tar.gz _site/
      - name: Upload to AliOSS
        uses: JohnGuan/oss-upload-action@main
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: ${{ secrets.OSS_REGION }}
          bucket: ${{ secrets.OSS_BUCKET }}
          assets: site.tar.gz:${{ env.RELEASE_AT }}/site.tar.gz
      - name: Release Zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: site.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
